### ISSUE TITLE
Create Application

### ISSUE THREAD

**Issue by tagnotfound** [BaritoLog/BaritoMarket#2]
*As* a product member
*I should* be able to create an app
*So that* I can start using BaritoLog to process and access my logs
- I should be able to specify the product I am requesting the logging for and which application group the product belongs to
- All the fields are required
- Transaction per second should all have the following values, refer to **TPS Configuration**
- Possible application groups are Mobility, Food, Logistics, Payments, Operations, we should be able to add application groups later
- By default, an application should have a status of pending setup until the infrastructure is provisioned
- By default, the application should be marked inactive

**TPS Configuration**
- Small (2 ZooKeeper, 2 Kafka, 2 Elastic Search, 1 Consul, 1 Yggradsil, 1 Kibana)
- Medium (4 ZooKeeper, 4 Kafka, 4 Elastic Search, 1 Consul, 1 Yggradsil, 1 Kibana)
- Large (8 ZooKeeper, 8 Kafka, 8 Elastic Search, 1 Consul, 1 Yggradsil, 1 Kibana)

**Comment by pushm0v** [comment]
@tagnotfound we will go with database for storing TPS configurations since its persistent & easy to maintain. ENV vars need to restart the app to get latest config, while we dont want this since BaritoMarket will handle application secret authentication for incoming logs.
