### ISSUE TITLE
Minor UI improvement on Market

### ISSUE THREAD

**Issue by pushm0v** [BaritoLog/BaritoMarket#86]
1. Show delete button in app groups list
2. When we changed AppGroup name, should also change it infrastructure name
3. Ordering of app list in app group should be sorted by ascending name

**Comment by giosakti** [comment]
`Show delete button in app groups list` -> this supposed to be showing a button that can toggle to show deleted app group, not delete button itself.. sorry for not making it clear. I'll put it as another issue
